name: sh67mmer

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        type: string

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board:
          - ambassador
          - banon
          - brask
          - brya
          - clapper
          - coral
          - corsola
          - cyan
          - dedede
          - edgar
          - elm
          - enguarde
          - fizz
          - glimmer
          - grunt
          - hana
          - hatch
          - jacuzzi
          - kalista
          - kefka
          - kukui
          - lulu
          - nami
          - nissa
          - octopus
          - orco
          - puff
          - pyro
          - reef
          - reks
          - relm
          - sand
          - sentry
          - snappy
          - stout
          - strongbad
          - tidus
          - trogdor
          - ultima
          - volteer
          - zork

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build sh67mmer
      env:
        board: ${{ matrix.board }}
      run: |
        set -e
        cd builder
        chmod +x ./sh67mmer.sh
        sudo apt install binwalk util-linux vboot-utils e2fsprogs coreutils cgpt pcregrep
        echo "Downloading file from https://dl.cros.download/files/${board}/${board}.zip..."
        wget -q "https://dl.cros.download/files/${board}/${board}.zip" -O "./${board}.zip" || exit 1
        unzip "./${board}.zip"
        shim=$(unzip -Z1 "./${board}.zip")
        shim=$(realpath -m "$shim")
        rm ./${board}.zip
        sudo ./sh67mmer.sh "$shim" 
        cd ../
        mv "$shim" ./sh67mmer-${board}.bin

    - name: Upload built shim
      uses: softprops/action-gh-release@v2
      with:
        name: sh67mmer ${{ inputs.tag }}
        tag_name: ${{ inputs.tag }}
        files: ./sh67mmer-${{ matrix.board }}.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
